import { COLORS } from "@/store/loop-game-instructions";

export type Loop = {
  c: COLORS;
  iS: boolean;
  iE: boolean;
};

export const gameLoop: Loop[][] = [
  [
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
  ],
  [
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
  ],
  [
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
  ],
  [
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
  ],
  [
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
  ],
  [
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "indigo", iS: false, iE: true },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
  ],
  [
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "indigo", iS: false, iE: false },
    { c: "indigo", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
  ],
  [
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "indigo", iS: false, iE: false },
    { c: "indigo", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
  ],
  [
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "indigo", iS: false, iE: false },
    { c: "indigo", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
  ],
  [
    { c: "", iS: false, iE: false },
    { c: "indigo", iS: true, iE: false },
    { c: "indigo", iS: false, iE: false },
    { c: "indigo", iS: false, iE: false },
    { c: "indigo", iS: false, iE: false },
    { c: "red", iS: false, iE: false },
    { c: "indigo", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
  ],
  [
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
  ],
  [
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
  ],
  [
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
    { c: "", iS: false, iE: false },
  ],
];
