export type Loop = {
  c: string;
  iS: boolean;
  iE: boolean;
};

export const gameLoop: Loop[][] = [
  [
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
  ],
  [
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
  ],
  [
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
  ],
  [
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
  ],
  [
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
  ],
  [
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "purple", iS: false, iE: true },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
  ],
  [
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "purple", iS: false, iE: false },
    { c: "purple", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
  ],
  [
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "purple", iS: false, iE: false },
    { c: "purple", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
  ],
  [
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "purple", iS: false, iE: false },
    { c: "purple", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
  ],
  [
    { c: "p", iS: false, iE: false },
    { c: "purple", iS: true, iE: false },
    { c: "purple", iS: false, iE: false },
    { c: "purple", iS: false, iE: false },
    { c: "purple", iS: false, iE: false },
    { c: "red", iS: false, iE: false },
    { c: "purple", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
  ],
  [
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
  ],
  [
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
  ],
  [
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
    { c: "p", iS: false, iE: false },
  ],
];
